[colors]
background = '#161616'
foreground = '#dde1e6'
selection-background = '#393939'
selection-foreground = '#f2f4f8'
cursor = '#dde1e6'
black = '#161616'
red = '#ee5396'
green = '#42be65'
yellow = '#82cfff'
blue = '#33b1ff'
magenta = '#be95ff'
cyan = '#08bdba'
white = '#dde1e6'
light_black = '#525252'
light_red = '#ff7eb6'
light_green = '#42be65'
light_yellow = '#82cfff'
light_blue = '#78a9ff'
light_magenta = '#be95ff'
light_cyan = '#3ddbd9'
light_white = '#f2f4f8'
