# yaml-language-server: $schema=https://gh-dash.dev/schema.json
prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me -author:app/dependabot
  - title: Charm
    filters: is:open user:charmbracelet -author:app/dependabot
  - title: Charm [bots]
    filters: is:pr is:open user:charmbracelet author:app/dependabot
  - title: caarlos0
    filters: is:open user:caarlos0 -author:app/dependabot
  - title: caarlos0 [bots]
    filters: is:pr is:open user:caarlos0 author:app/dependabot
  - title: GoReleaser
    filters: is:open user:goreleaser -author:app/dependabot
  - title: GoReleaser [bots]
    filters: is:pr is:open user:goreleaser author:app/dependabot
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Charm
    filters: is:open user:charmbracelet
  - title: GoReleaser
    filters: is:open user:goreleaser
  - title: caarlos0
    filters: is:open user:caarlos0
defaults:
  preview:
    open: false
    width: 80
  prsLimit: 25
  issuesLimit: 25
  view: prs
  layout:
    prs:
      repo:
        grow: true
        width: 25
        hidden: false
    issues:
      repo:
        grow: true
        width: 25
        hidden: false
repoPaths:
  caarlos0/*: ~/Developer/caarlos0/*
  goreleaser/*: ~/Developer/goreleaser/*
  charmbracelet/*: ~/Developer/charmbracelet/*
pager:
  diff: delta
keybindings:
  prs:
    - key: N
      command: >
        gh pr comment --repo {{.RepoName}} {{.PrNumber}} --body "@dependabot rebase"
    - key: M
      command: >
        gh pr review --repo {{.RepoName}} {{.PrNumber}} --approve &&
        gh pr merge --repo {{.RepoName}} {{.PrNumber}} --admin --squash --delete-branch
